-d C:\Gowin\Gowin_V1.9.9.03_Education_x64\IDE\bin\Documents\SPI_MRAM_Truncated\impl\gwsynthesis\SPI_MRAM_Truncated.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Gowin\Gowin_V1.9.9.03_Education_x64\IDE\bin\Documents\SPI_MRAM_Truncated\src\SPI_MRAM_Truncated.cst
-cfg C:\Gowin\Gowin_V1.9.9.03_Education_x64\IDE\bin\Documents\SPI_MRAM_Truncated\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
