@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 19 01:29:17 +0800 2025
REM SW Build 5094488 on Fri Jun 14 08:59:21 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Integrate_Top_Module_tb_behav -key {Behavioral:sim_1:Functional:Integrate_Top_Module_tb} -tclbatch Integrate_Top_Module_tb.tcl -view C:/Users/yeohw/OneDrive/Desktop/FYP/Integration/Integrate_Top_Module_tb_behav.wcfg -log simulate.log"
call xsim  Integrate_Top_Module_tb_behav -key {Behavioral:sim_1:Functional:Integrate_Top_Module_tb} -tclbatch Integrate_Top_Module_tb.tcl -view C:/Users/yeohw/OneDrive/Desktop/FYP/Integration/Integrate_Top_Module_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
