M48
; DRILL file {KiCad 8.0.4} date 2024-09-23T22:15:29+0800
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2024-09-23T22:15:29+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X116200Y-55400
X116200Y-145900
X186500Y-55400
X186500Y-145900
M30
